apiVersion: v1
kind: ResourceQuota
metadata:
  name: runner-quota
  namespace: github-runners
spec:
  hard:
    requests.cpu: "20"         # 7 runners @ ~2 cores each
    requests.memory: "35Gi"    # 7 runners @ 4-5GB each
    limits.cpu: "60"           # Allow bursting
    limits.memory: "60Gi"      # Allow bursting (but under node capacity)
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: runner-limits
  namespace: github-runners
spec:
  limits:
  - max:
      cpu: "8"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "2"
      memory: "4Gi"
    type: Container