---
# Add docker group GID to runner pods for socket access
# This ensures proper permissions without full privileged mode in some cases
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-cleanup
  namespace: github-runners
data:
  cleanup.sh: |
    #!/bin/bash
    # Cleanup script to remove dangling containers/images
    # Run this periodically to prevent disk exhaustion
    
    echo "$(date): Starting Docker cleanup..."
    
    # Remove stopped containers older than 1 hour
    docker container prune -f --filter "until=1h"
    
    # Remove dangling images
    docker image prune -f
    
    # Remove unused volumes
    docker volume prune -f
    
    # Remove build cache older than 24 hours
    docker builder prune -f --filter "until=24h"
    
    echo "$(date): Cleanup complete"
---
# CronJob to periodically clean up Docker resources
apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-cleanup
  namespace: github-runners
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: cloudv10x/github-actions-riscv:docker-latest
            command:
            - /bin/bash
            - /scripts/cleanup.sh
            volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: cleanup-script
              mountPath: /scripts
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
          - name: cleanup-script
            configMap:
              name: docker-cleanup
              defaultMode: 0755