# base/resource-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: runner-quota
  namespace: github-runners
spec:
  hard:
    requests.cpu: "60"         # Allow 3 runners @ 18 cores each (16+2)
    requests.memory: "120Gi"   # Allow 3 runners @ 20GB each (16+4)
    limits.cpu: "120"          # Allow bursting (3 runners @ 36 cores = 108)
    limits.memory: "240Gi"     # Allow bursting (3 runners @ 64GB = 192)
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: runner-limits
  namespace: github-runners
spec:
  limits:
  - max:
      cpu: "36"                # Per container max (32+4)
      memory: "64Gi"           # Per container max (48+16)
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "18"
      memory: "20Gi"
    defaultRequest:
      cpu: "18"
      memory: "20Gi"
    type: Container