# base/resource-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: runner-quota
  namespace: github-runners
spec:
  hard:
    requests.cpu: "40"
    requests.memory: "80Gi"
    limits.cpu: "80"
    limits.memory: "160Gi"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: runner-limits
  namespace: github-runners
spec:
  limits:
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    type: Container
  - max:
      ephemeral-storage: "100Gi"
    type: Pod